# -*- coding: utf-8 -*-
# Generated by Django 1.11.20 on 2019-03-21 19:07
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('albums', '0002_auto_20190321_1845'),
    ]

    operations = [
        migrations.RenameField(
            model_name='artistgroup',
            old_name='type',
            new_name='otype',
        ),
    ]
