# -*- coding: utf-8 -*-
# Generated by Django 1.11.20 on 2019-03-21 20:34
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('albums', '0006_auto_20190321_2032'),
    ]

    operations = [
        migrations.AlterField(
            model_name='album',
            name='artist',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='albums.ArtistGroup'),
        ),
    ]
